import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Copy, Check, Share2, ThumbsUp, ThumbsDown, Send } from "lucide-react";
import { toast } from "sonner";

interface ResponseActionsProps {
  challenge: string;
  phases: { empathy: string; shared_value: string; message: string };
}

const ResponseActions = ({ challenge, phases }: ResponseActionsProps) => {
  const [copied, setCopied] = useState(false);
  const [rating, setRating] = useState<"up" | "down" | null>(null);
  const [showFeedback, setShowFeedback] = useState(false);
  const [feedback, setFeedback] = useState("");
  const [feedbackSent, setFeedbackSent] = useState(false);

  const fullText = `Concern: "${challenge}"\n\n` +
    `Acknowledgment:\n${phases.empathy}\n\n` +
    `Shared Values:\n${phases.shared_value}\n\n` +
    `A Truth-Based Message:\n${phases.message}\n\n` +
    `— Generated by Alderos`;

  const handleCopy = async () => {
    await navigator.clipboard.writeText(fullText);
    setCopied(true);
    toast.success("Copied to clipboard");
    setTimeout(() => setCopied(false), 2000);
  };

  const handleWhatsApp = () => {
    const url = `https://wa.me/?text=${encodeURIComponent(fullText)}`;
    window.open(url, "_blank");
  };

  const handleRate = (value: "up" | "down") => {
    setRating(value);
    if (value === "down") {
      setShowFeedback(true);
    } else {
      toast.success("Thank you for your feedback!");
    }
  };

  const handleSendFeedback = () => {
    setFeedbackSent(true);
    setShowFeedback(false);
    toast.success("Thank you — your feedback helps us improve.");
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.3, duration: 0.5 }}
      className="max-w-2xl mx-auto mt-10"
    >
      {/* Action buttons */}
      <div className="flex items-center justify-center gap-3 mb-6">
        <button
          onClick={handleCopy}
          className="flex items-center gap-2 px-4 py-2 rounded-full text-xs font-body
                     border border-border hover:border-accent/30 hover:bg-accent/5 transition-all"
        >
          {copied ? <Check className="w-3.5 h-3.5 text-green-600" /> : <Copy className="w-3.5 h-3.5 text-muted-foreground" />}
          {copied ? "Copied" : "Copy"}
        </button>

        <button
          onClick={handleWhatsApp}
          className="flex items-center gap-2 px-4 py-2 rounded-full text-xs font-body
                     border border-border hover:border-accent/30 hover:bg-accent/5 transition-all"
        >
          <Share2 className="w-3.5 h-3.5 text-muted-foreground" />
          Share via WhatsApp
        </button>
      </div>

      {/* Rating */}
      <div className="flex flex-col items-center gap-3">
        <p className="text-xs text-muted-foreground font-body">Was this reframing helpful?</p>
        <div className="flex gap-2">
          <button
            onClick={() => handleRate("up")}
            className={`p-2.5 rounded-full border transition-all ${
              rating === "up"
                ? "border-accent bg-accent/10 text-accent"
                : "border-border text-muted-foreground hover:border-accent/30"
            }`}
          >
            <ThumbsUp className="w-4 h-4" />
          </button>
          <button
            onClick={() => handleRate("down")}
            className={`p-2.5 rounded-full border transition-all ${
              rating === "down"
                ? "border-accent bg-accent/10 text-accent"
                : "border-border text-muted-foreground hover:border-accent/30"
            }`}
          >
            <ThumbsDown className="w-4 h-4" />
          </button>
        </div>

        <AnimatePresence>
          {showFeedback && !feedbackSent && (
            <motion.div
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: "auto" }}
              exit={{ opacity: 0, height: 0 }}
              className="w-full max-w-md overflow-hidden"
            >
              <div className="pt-3">
                <textarea
                  value={feedback}
                  onChange={(e) => setFeedback(e.target.value)}
                  placeholder="What could be improved?"
                  className="w-full h-20 px-4 py-3 rounded-xl border border-border bg-card text-foreground
                             placeholder:text-muted-foreground/50 resize-none font-body text-xs
                             focus:outline-none focus:ring-2 focus:ring-accent/20 transition-all"
                />
                <div className="flex justify-end mt-2">
                  <button
                    onClick={handleSendFeedback}
                    disabled={!feedback.trim()}
                    className="flex items-center gap-1.5 px-4 py-2 bg-primary text-primary-foreground rounded-full
                               font-body text-xs disabled:opacity-40 hover:opacity-90 transition-opacity"
                  >
                    <Send className="w-3 h-3" />
                    Send feedback
                  </button>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </motion.div>
  );
};

export default ResponseActions;
